name:                haskell-stack
version:             0.1.0.0
github:              "dhinojosa/haskell-stack"
license:             BSD3
author:              "Daniel Hinojosa"
maintainer:          "dhinojosa@evolutionnext.com"
copyright:           "Daniel Hinojosa"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dhinojosa/haskell-stack#readme>

dependencies:
- base >= 4.7 && < 5
- extra >= 1.7.8 && < 1.8

library:
  source-dirs: src

executables:
  haskell-stack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-stack

tests:
  haskell-stack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-stack
    - HUnit
